# Generated by Django 6.0.4 on 2026-04-17 19:04

import core.db.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('external_id', models.BigIntegerField(unique=True, verbose_name='Внешний ID клиента')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, max_length=32, verbose_name='Пол')),
                ('parent_primary', models.CharField(blank=True, max_length=255, verbose_name='Родитель 1')),
                ('parent_secondary', models.CharField(blank=True, max_length=255, verbose_name='Родитель 2')),
                ('student_status', models.CharField(blank=True, max_length=64, verbose_name='Статус ученика')),
                ('student_tag', models.CharField(blank=True, max_length=255, verbose_name='Тег ученика')),
                ('student_branch', models.CharField(blank=True, max_length=255, verbose_name='Филиал ученика')),
                ('can_receive', models.BooleanField(default=False, verbose_name='Подписан на рассылку')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.SlugField(max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('telegram_bot', 'Telegram Bot')], max_length=32, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('secrets', core.db.fields.EncryptedJSONField(blank=True, default=dict, verbose_name='Секреты')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'code'), name='uq_channel_config_type_code')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('processing', 'Отправляется'), ('completed', 'Завершена'), ('partial', 'Завершена с ошибками'), ('failed', 'Ошибка')], default='draft', max_length=32, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт отправки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание отправки')),
                ('filter_payload', models.JSONField(blank=True, default=dict, verbose_name='Фильтр аудитории')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('channel_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.channelconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram'), ('vk', 'VK'), ('max', 'MAX')], max_length=32, verbose_name='Тип контакта')),
                ('label', models.CharField(blank=True, choices=[('primary', 'Родитель 1'), ('secondary', 'Родитель 2'), ('extra', 'Дополнительный')], max_length=32, verbose_name='Метка')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('unsubscribed', 'Отписан'), ('invalid', 'Невалиден')], default='active', max_length=32, verbose_name='Статус')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('retry', 'Повтор'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=32, verbose_name='Статус')),
                ('recipient_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Снимок адреса')),
                ('provider_recipient_id', models.CharField(blank=True, max_length=255, verbose_name='ID получателя у провайдера')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID сообщения у провайдера')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.campaign')),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.clientcontact')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(fields=('client', 'type', 'value'), name='uq_client_contact_type_value'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('campaign', 'client_contact'), name='uq_delivery_campaign_contact'),
        ),
    ]
